name: Build and Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_DIR: ${{github.workspace}}/build

jobs:
  matrix-build:
    strategy:
      matrix:
        os: [ 'ubuntu-latest', 'windows-latest' ]
        build_type: [ 'Release', 'Debug' ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Configure CMake
        run: cmake -S . -B ${{ env.BUILD_DIR }} -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

      - name: Build
        run: cmake --build ${{ env.BUILD_DIR }} --config ${{ matrix.build_type }} --target fake test

      - name: Test
        working-directory: ${{ env.BUILD_DIR }}/gtest
        run: ctest -C ${{ matrix.build_type }}

      - name: Test itself
        run: ${{ env.BUILD_DIR }}/fake run-tests
